version: "3"
services:
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
    # command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  api:
    links:
      - mongo
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - backend/.env

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodata/data:/data/db
      - ./mongodata/log:/data/log

  mongo-express:
    links:
      - mongo
    ports:
      - "8081:8081"
    image: mongo-express
    restart: always
