version: "3"
services:
  # nginx:
  #   image: nginx:1.15-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/log:/var/log/nginx
  #     - ./frontend/dist/:/var/www/web
  #     - ./nginx/conf:/etc/nginx/conf.d
  #   command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  api:
    links:
      - mongo
    build:
      context: ./backend
      dockerfile:prod.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    command: node server

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodata/data:/data/db
      - ./mongodata/log:/data/log

  mongo-express:
    links:
      - mongo
    image: mongo-express
    restart: always
