version: "3"
services:
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    env_file:
      - frontend/.env
    volumes:
      - ./frontend/src:/home/node/app/src
    command: npm run parcel:start

  backend:
    links:
      - mongo
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/src:/home/node/app/src
    command: npm run develop

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodata/data:/data/db
      - ./mongodata/log:/data/log

  mongo-express:
    links:
      - mongo
    ports:
      - 8081:8081
    image: mongo-express
    restart: always
