version: "3"
services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9090:9090"
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/www/:/var/www/web
      - ./nginx/conf:/etc/nginx/conf.d
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  backend:
    links:
      - mongo
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/home/node/app
    env_file:
      - backend/.env
    command: npm run develop

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/home/node/app
  #   env_file:
  #     - frontend/.env
  #   command: npm start

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodata/data:/data/db
      - ./mongodata/log:/data/log

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
